name: randuraft_web_app
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <3.16.9'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  firebase_core: ^2.7.0
  cloud_firestore: ^4.4.3
  firebase_crashlytics: ^3.0.15
  firebase_analytics: ^10.1.4
  firebase_remote_config: ^4.3.13
  firebase_messaging: ^14.2.5
  firebase_auth: ^4.2.9
  firebase_core_web: ^2.6.0
  freezed_annotation: ^2.1.0
  simple_logger: ^1.9.0
  flame: ^1.8.2
  http: ^1.2.0
  dart_openai: ^5.0.0
  flutter_dotenv: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.8
  freezed: ^2.0.0
  flutter_lints: ^3.0.1
  build: ^2.4.1

flutter:
  assets:
    - assets/images/
  uses-material-design: true
