name: Flutter CI

on:
  pull_request:
    branches:
      - develop
    paths:
      - "dennys_web_app/**"
      - "!dennys_web_app/**.md"
  push:
    branches:
      - develop
    paths:
      - "dennys_web_app/**"
      - "!dennys_web_app/**.md"

jobs:
  flutter-lint-format:
    runs-on: ubuntu-latest
    name: Lint and Format Check
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.0.5'
      - name: Install dependencies
        run: flutter pub get
      - name: Run flutter format
        run: flutter format --set-exit-if-changed .
      - name: Run flutter analyze
        run: flutter analyze
