name: Flutter CI

on:
  pull_request:
    branches:
      - main
    paths:
      - '**/*.dart'
  push:
    branches:
      - main
    paths:
      - '**/*.dart'

jobs:
  flutter-lint-format:
    runs-on: ubuntu-latest
    name: Lint and Format Check
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.16.9'
      - name: Install dependencies
        working-directory: ./randuraft_web_app
        run: flutter pub get
      - name: Run dart format
        working-directory: ./randuraft_web_app
        run: dart format --set-exit-if-changed .
      - name: Run dart analyze
        working-directory: ./randuraft_web_app
        run: dart analyze
      - name: Run flutter analyze
        working-directory: ./randuraft_web_app
        run: flutter analyze
      
      - name: Load Firebase Secrets
        run: |
          echo "FIREBASE_API_KEY=${{ secrets.FIREBASE_API_KEY }}" >> $GITHUB_ENV
          echo "FIREBASE_AUTH_DOMAIN=${{ secrets.FIREBASE_AUTH_DOMAIN }}" >> $GITHUB_ENV
          echo "FIREBASE_PROJECT_ID=${{ secrets.FIREBASE_PROJECT_ID }}" >> $GITHUB_ENV
          echo "FIREBASE_STORAGE_BUCKET=${{ secrets.FIREBASE_STORAGE_BUCKET }}" >> $GITHUB_ENV
          echo "FIREBASE_MESSAGING_SENDER_ID=${{ secrets.FIREBASE_MESSAGING_SENDER_ID }}" >> $GITHUB_ENV
          echo "FIREBASE_APP_ID=${{ secrets.FIREBASE_APP_ID }}" >> $GITHUB_ENV
          echo "FIREBASE_MEASUREMENT_ID=${{ secrets.FIREBASE_MEASUREMENT_ID }}" >> $GITHUB_ENV
      - name: Run tests
        working-directory: ./randuraft_web_app/lib
        run: flutter test
