name: python CI

on:
  pull_request:
    branches: [main]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      
      - name: Install pipx
        run: python -m pip install pipx && pipx ensurepath
      
      - name: Install Poetry
        run: pipx install poetry
      
      - name: Find directories, install dependencies, format, lint, and test
        run: |
          for dir in */ ; do
            if [[ -f "${dir}pyproject.toml" ]]; then
              echo "Processing ${dir}..."
              cd "${dir}"
              poetry install --no-root
              echo "Running formatter..."
              poetry run black --check .
              echo "Running linter..."
              poetry run mypy .
              echo "Running tests..."
              poetry run pytest
              cd ..
            else
              echo "No pyproject.toml found in ${dir}, skipping..."
            fi
          done